services:
  backend:
    build: ./backend
    container_name: payflow-ai-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: payflow-ai-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
